# Selected - 100 numpy exercises with hint

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel free to open an issue at <https://github.com/rougier/numpy-100>

#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [2]:
np.__version__

'1.13.3'

#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [3]:
v = np.zeros(10)
v

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [4]:
np.size(v)

10

#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [5]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [23]:
np.arange(10) == 4

array([False, False, False, False,  True, False, False, False, False, False], dtype=bool)

In [26]:

(np.arange(10) == 4).view(np.uint8)

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0], dtype=uint8)

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [28]:
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [6]:
vr = v[::-1]
vr

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [29]:
Z = np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [30]:
q = np.nonzero([1,2,0,0,4,0])
print(q)

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [31]:
Z = np.eye(3)
print(Z)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [32]:
Z = np.random.random((3,3,3))
print(Z)

[[[ 0.63131919  0.61503852  0.23806686]
  [ 0.98884538  0.75006369  0.67559475]
  [ 0.78742043  0.30870059  0.83675645]]

 [[ 0.96996218  0.27222897  0.6812782 ]
  [ 0.33252106  0.44544383  0.7386663 ]
  [ 0.52968878  0.19196559  0.17201164]]

 [[ 0.68783766  0.32731291  0.66518444]
  [ 0.49946332  0.16446138  0.94367186]
  [ 0.5336546   0.48971966  0.68858462]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [35]:
#mention argmax
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.00620352117201 0.981267275674


#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [34]:
#along the axis too
Z = np.random.random(30)
m = Z.mean()
print(m)

0.425328814139


#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [9]:
#0 * np.nan
#np.nan == np.nan
#np.inf > np.nan
#np.nan - np.nan
#0.3 == 3.0 * 0.1

#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [36]:
Z = np.random.random((5,5))
Zmax, Zmin = Z.max(), Z.min()
Z = (Z - Zmin)/(Zmax - Zmin)
print(Z)

[[ 0.962883    0.66233333  0.29775024  0.71135639  0.94923174]
 [ 0.28498216  0.68790888  0.28170552  0.44759516  0.37727981]
 [ 0.97215136  0.1627129   0.82201797  0.82412968  0.        ]
 [ 0.37649305  0.42383403  0.11044676  0.46086526  0.33098419]
 [ 1.          0.41665152  0.60623546  0.69849301  0.75785627]]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [37]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

[[ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [10]:
v = np.arange(15)
v
v[(v>3) & (v<8)] *= -1
v

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10, 11, 12, 13, 14])

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [11]:
np.multiply(np.add(a,b),np.divide(np.multiply(a,-1),2))

NameError: name 'a' is not defined

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [12]:
Z = np.random.uniform(0,10,10)
Z.astype(int)
print (np.trunc(Z))


[ 0.  9.  9.  6.  2.  9.  2.  1.  3.  2.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [38]:
#broadcasting
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [14]:
import numpy as np

Z = np.linspace(0,1,11,endpoint=True)[1:-1]
print(Z)

[ 0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9]


#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [15]:
v = np.random.randint(10,102,(1,10))
print (v)

[[20 28 39 29 51 70 71 88 23 45]]


#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [39]:
# whats rtol and atol
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = np.allclose(A,B)
print(equal)

False


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [17]:
v = np.random.rand(10)
v
v.sort()
v[-1]

0.98386623958934127

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [18]:
a = np.random.random(10)
a
b = np.random.random(10)
b

c = np.subtract(a,b)
c

d= np.subtract.outer(a,b)
d

array([[  2.11530904e-01,  -2.89261724e-01,   3.07273679e-01,
          1.71859491e-01,   3.80535187e-01,   6.08186177e-01,
         -1.72004604e-01,  -2.18415493e-01,  -8.50172047e-02,
          3.01266948e-01],
       [ -1.69465146e-01,  -6.70257774e-01,  -7.37223716e-02,
         -2.09136559e-01,  -4.60863268e-04,   2.27190127e-01,
         -5.53000655e-01,  -5.99411543e-01,  -4.66013255e-01,
         -7.97291022e-02],
       [ -1.70973944e-01,  -6.71766571e-01,  -7.52311688e-02,
         -2.10645357e-01,  -1.96966053e-03,   2.25681330e-01,
         -5.54509452e-01,  -6.00920341e-01,  -4.67522052e-01,
         -8.12378995e-02],
       [  5.55278819e-01,   5.44861913e-02,   6.51021594e-01,
          5.15607406e-01,   7.24283102e-01,   9.51934092e-01,
          1.71743311e-01,   1.25332422e-01,   2.58730710e-01,
          6.45014863e-01],
       [ -8.96952248e-03,  -5.09762150e-01,   8.67732522e-02,
         -4.86409356e-02,   1.60034761e-01,   3.87685751e-01,
         -3.92505031e-01

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [19]:
for i,j in enumerate(np.arange(10)):
  print (i,j)

0 0
1 1
2 2
3 3
4 4
5 5
6 6
7 7
8 8
9 9


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [42]:
X = np.random.rand(5, 10)
Y = X - X.mean(axis=1, keepdims=True)


#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [43]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[9 3 3]
 [4 5 5]
 [4 5 2]]
[[9 3 3]
 [4 5 5]
 [4 5 2]]


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

SyntaxError: invalid syntax (<ipython-input-46-7fd016175311>, line 1)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [20]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]]

 [[ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]]

 [[ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]]

 [[ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]]

 [[ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [47]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [21]:
Z = np.random.randint(0,10,50)
np.bincount(Z)
#print(np.bincount(Z).argmax())

array([ 4,  4,  1,  6, 11,  7,  5,  4,  4,  4])